name: CI Docs

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validar docs
        run: echo "Docs OK"
